export const ebTenebresEmbrasees = {
  cardCount: {
    firstEd: 0,
    holo: 64,
    normal: 137,
    official: 189,
    reverse: 155,
    total: 201,
  },
  cards: [
    {
      id: "swsh3-1",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/1/high.webp",
      localId: "1",
      name: "Papilusion V",
    },
    {
      id: "swsh3-2",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/2/high.webp",
      localId: "2",
      name: "Papilusion VMAX",
    },
    {
      id: "swsh3-3",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/3/high.webp",
      localId: "3",
      name: "Paras",
    },
    {
      id: "swsh3-4",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/4/high.webp",
      localId: "4",
      name: "Parasect",
    },
    {
      id: "swsh3-5",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/5/high.webp",
      localId: "5",
      name: "Vortente",
    },
    {
      id: "swsh3-6",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/6/high.webp",
      localId: "6",
      name: "Feuillajou",
    },
    {
      id: "swsh3-7",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/7/high.webp",
      localId: "7",
      name: "Feuiloutan",
    },
    {
      id: "swsh3-8",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/8/high.webp",
      localId: "8",
      name: "Carabing",
    },
    {
      id: "swsh3-9",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/9/high.webp",
      localId: "9",
      name: "Escargaume",
    },
    {
      id: "swsh3-10",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/10/high.webp",
      localId: "10",
      name: "Limaspeed",
    },
    {
      id: "swsh3-11",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/11/high.webp",
      localId: "11",
      name: "Brindibou",
    },
    {
      id: "swsh3-12",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/12/high.webp",
      localId: "12",
      name: "Efflèche",
    },
    {
      id: "swsh3-13",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/13/high.webp",
      localId: "13",
      name: "Archéduc",
    },
    {
      id: "swsh3-14",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/14/high.webp",
      localId: "14",
      name: "Croquine",
    },
    {
      id: "swsh3-15",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/15/high.webp",
      localId: "15",
      name: "Candine",
    },
    {
      id: "swsh3-16",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/16/high.webp",
      localId: "16",
      name: "Sucreine",
    },
    {
      id: "swsh3-17",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/17/high.webp",
      localId: "17",
      name: "Sovkipou",
    },
    {
      id: "swsh3-18",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/18/high.webp",
      localId: "18",
      name: "Sarmuraï",
    },
    {
      id: "swsh3-19",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/19/high.webp",
      localId: "19",
      name: "Dracaufeu V",
    },
    {
      id: "swsh3-20",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/20/high.webp",
      localId: "20",
      name: "Dracaufeu VMAX",
    },
    {
      id: "swsh3-21",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/21/high.webp",
      localId: "21",
      name: "Démolosse V",
    },
    {
      id: "swsh3-22",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/22/high.webp",
      localId: "22",
      name: "Poussifeu",
    },
    {
      id: "swsh3-23",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/23/high.webp",
      localId: "23",
      name: "Galifeu",
    },
    {
      id: "swsh3-24",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/24/high.webp",
      localId: "24",
      name: "Braségali",
    },
    {
      id: "swsh3-25",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/25/high.webp",
      localId: "25",
      name: "Heatran",
    },
    {
      id: "swsh3-26",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/26/high.webp",
      localId: "26",
      name: "Flamajou",
    },
    {
      id: "swsh3-27",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/27/high.webp",
      localId: "27",
      name: "Flamoutan",
    },
    {
      id: "swsh3-28",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/28/high.webp",
      localId: "28",
      name: "Darumacho de Galar",
    },
    {
      id: "swsh3-29",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/29/high.webp",
      localId: "29",
      name: "Pyronille",
    },
    {
      id: "swsh3-30",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/30/high.webp",
      localId: "30",
      name: "Pyrax",
    },
    {
      id: "swsh3-31",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/31/high.webp",
      localId: "31",
      name: "Braisillon",
    },
    {
      id: "swsh3-32",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/32/high.webp",
      localId: "32",
      name: "Flambusard",
    },
    {
      id: "swsh3-33",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/33/high.webp",
      localId: "33",
      name: "Scolocendre V",
    },
    {
      id: "swsh3-34",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/34/high.webp",
      localId: "34",
      name: "Scolocendre VMAX",
    },
    {
      id: "swsh3-35",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/35/high.webp",
      localId: "35",
      name: "M. Mime de Galar",
    },
    {
      id: "swsh3-36",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/36/high.webp",
      localId: "36",
      name: "M. Glaquette de Galar",
    },
    {
      id: "swsh3-37",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/37/high.webp",
      localId: "37",
      name: "Suicune",
    },
    {
      id: "swsh3-38",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/38/high.webp",
      localId: "38",
      name: "Barpau",
    },
    {
      id: "swsh3-39",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/39/high.webp",
      localId: "39",
      name: "Milobellus",
    },
    {
      id: "swsh3-40",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/40/high.webp",
      localId: "40",
      name: "Relicanth",
    },
    {
      id: "swsh3-41",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/41/high.webp",
      localId: "41",
      name: "Flotajou",
    },
    {
      id: "swsh3-42",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/42/high.webp",
      localId: "42",
      name: "Flotoutan",
    },
    {
      id: "swsh3-43",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/43/high.webp",
      localId: "43",
      name: "Darumarond de Galar",
    },
    {
      id: "swsh3-44",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/44/high.webp",
      localId: "44",
      name: "Darumacho de Galar",
    },
    {
      id: "swsh3-45",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/45/high.webp",
      localId: "45",
      name: "Sorbébé",
    },
    {
      id: "swsh3-46",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/46/high.webp",
      localId: "46",
      name: "Sorboul",
    },
    {
      id: "swsh3-47",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/47/high.webp",
      localId: "47",
      name: "Sorbouboul",
    },
    {
      id: "swsh3-48",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/48/high.webp",
      localId: "48",
      name: "Polarhume",
    },
    {
      id: "swsh3-49",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/49/high.webp",
      localId: "49",
      name: "Polagriffe",
    },
    {
      id: "swsh3-50",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/50/high.webp",
      localId: "50",
      name: "Froussardine",
    },
    {
      id: "swsh3-51",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/51/high.webp",
      localId: "51",
      name: "Vorastérie",
    },
    {
      id: "swsh3-52",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/52/high.webp",
      localId: "52",
      name: "Prédastérie",
    },
    {
      id: "swsh3-53",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/53/high.webp",
      localId: "53",
      name: "Hydragon",
    },
    {
      id: "swsh3-54",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/54/high.webp",
      localId: "54",
      name: "Hydragla",
    },
    {
      id: "swsh3-55",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/55/high.webp",
      localId: "55",
      name: "Wattouat",
    },
    {
      id: "swsh3-56",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/56/high.webp",
      localId: "56",
      name: "Lainergie",
    },
    {
      id: "swsh3-57",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/57/high.webp",
      localId: "57",
      name: "Pharamp",
    },
    {
      id: "swsh3-58",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/58/high.webp",
      localId: "58",
      name: "Dynavolt",
    },
    {
      id: "swsh3-59",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/59/high.webp",
      localId: "59",
      name: "Élecsprint",
    },
    {
      id: "swsh3-60",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/60/high.webp",
      localId: "60",
      name: "Lucanon V",
    },
    {
      id: "swsh3-61",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/61/high.webp",
      localId: "61",
      name: "Tokorico",
    },
    {
      id: "swsh3-62",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/62/high.webp",
      localId: "62",
      name: "Toxizap",
    },
    {
      id: "swsh3-63",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/63/high.webp",
      localId: "63",
      name: "Salarsen",
    },
    {
      id: "swsh3-64",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/64/high.webp",
      localId: "64",
      name: "Wattapik",
    },
    {
      id: "swsh3-65",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/65/high.webp",
      localId: "65",
      name: "Galvagon",
    },
    {
      id: "swsh3-66",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/66/high.webp",
      localId: "66",
      name: "Galvagla",
    },
    {
      id: "swsh3-67",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/67/high.webp",
      localId: "67",
      name: "Rondoudou",
    },
    {
      id: "swsh3-68",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/68/high.webp",
      localId: "68",
      name: "Grodoudou",
    },
    {
      id: "swsh3-69",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/69/high.webp",
      localId: "69",
      name: "Mew V",
    },
    {
      id: "swsh3-70",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/70/high.webp",
      localId: "70",
      name: "Snubbull",
    },
    {
      id: "swsh3-71",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/71/high.webp",
      localId: "71",
      name: "Granbull",
    },
    {
      id: "swsh3-72",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/72/high.webp",
      localId: "72",
      name: "Séléroc",
    },
    {
      id: "swsh3-73",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/73/high.webp",
      localId: "73",
      name: "Scrutella",
    },
    {
      id: "swsh3-74",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/74/high.webp",
      localId: "74",
      name: "Mesmérella",
    },
    {
      id: "swsh3-75",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/75/high.webp",
      localId: "75",
      name: "Sidérella",
    },
    {
      id: "swsh3-76",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/76/high.webp",
      localId: "76",
      name: "Gringolem",
    },
    {
      id: "swsh3-77",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/77/high.webp",
      localId: "77",
      name: "Golemastoc",
    },
    {
      id: "swsh3-78",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/78/high.webp",
      localId: "78",
      name: "Dedenne",
    },
    {
      id: "swsh3-79",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/79/high.webp",
      localId: "79",
      name: "Spododo",
    },
    {
      id: "swsh3-80",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/80/high.webp",
      localId: "80",
      name: "Lampignon",
    },
    {
      id: "swsh3-81",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/81/high.webp",
      localId: "81",
      name: "Mimiqui",
    },
    {
      id: "swsh3-82",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/82/high.webp",
      localId: "82",
      name: "Théffroi",
    },
    {
      id: "swsh3-83",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/83/high.webp",
      localId: "83",
      name: "Polthégeist",
    },
    {
      id: "swsh3-84",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/84/high.webp",
      localId: "84",
      name: "Taupiqueur",
    },
    {
      id: "swsh3-85",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/85/high.webp",
      localId: "85",
      name: "Triopikeur",
    },
    {
      id: "swsh3-86",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/86/high.webp",
      localId: "86",
      name: "Embrylex",
    },
    {
      id: "swsh3-87",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/87/high.webp",
      localId: "87",
      name: "Ymphect",
    },
    {
      id: "swsh3-88",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/88/high.webp",
      localId: "88",
      name: "Tyranocif",
    },
    {
      id: "swsh3-89",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/89/high.webp",
      localId: "89",
      name: "Kraknoix",
    },
    {
      id: "swsh3-90",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/90/high.webp",
      localId: "90",
      name: "Vibraninf",
    },
    {
      id: "swsh3-91",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/91/high.webp",
      localId: "91",
      name: "Libégon",
    },
    {
      id: "swsh3-92",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/92/high.webp",
      localId: "92",
      name: "Solaroc",
    },
    {
      id: "swsh3-93",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/93/high.webp",
      localId: "93",
      name: "Hippopotas",
    },
    {
      id: "swsh3-94",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/94/high.webp",
      localId: "94",
      name: "Hippodocus",
    },
    {
      id: "swsh3-95",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/95/high.webp",
      localId: "95",
      name: "Rhinastoc V",
    },
    {
      id: "swsh3-96",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/96/high.webp",
      localId: "96",
      name: "Excavarenne",
    },
    {
      id: "swsh3-97",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/97/high.webp",
      localId: "97",
      name: "Quartermac",
    },
    {
      id: "swsh3-98",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/98/high.webp",
      localId: "98",
      name: "Palarticho de Galar",
    },
    {
      id: "swsh3-99",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/99/high.webp",
      localId: "99",
      name: "Flagadoss de Galar V",
    },
    {
      id: "swsh3-100",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/100/high.webp",
      localId: "100",
      name: "Tadmorv",
    },
    {
      id: "swsh3-101",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/101/high.webp",
      localId: "101",
      name: "Grotadmorv",
    },
    {
      id: "swsh3-102",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/102/high.webp",
      localId: "102",
      name: "Mimigal",
    },
    {
      id: "swsh3-103",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/103/high.webp",
      localId: "103",
      name: "Migalos",
    },
    {
      id: "swsh3-104",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/104/high.webp",
      localId: "104",
      name: "Nostenfer V",
    },
    {
      id: "swsh3-105",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/105/high.webp",
      localId: "105",
      name: "Darkrai",
    },
    {
      id: "swsh3-106",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/106/high.webp",
      localId: "106",
      name: "Chacripan",
    },
    {
      id: "swsh3-107",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/107/high.webp",
      localId: "107",
      name: "Léopardus",
    },
    {
      id: "swsh3-108",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/108/high.webp",
      localId: "108",
      name: "Solochi",
    },
    {
      id: "swsh3-109",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/109/high.webp",
      localId: "109",
      name: "Diamat",
    },
    {
      id: "swsh3-110",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/110/high.webp",
      localId: "110",
      name: "Trioxhydre",
    },
    {
      id: "swsh3-111",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/111/high.webp",
      localId: "111",
      name: "Hoopa",
    },
    {
      id: "swsh3-112",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/112/high.webp",
      localId: "112",
      name: "Goupilou",
    },
    {
      id: "swsh3-113",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/113/high.webp",
      localId: "113",
      name: "Roublenard",
    },
    {
      id: "swsh3-114",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/114/high.webp",
      localId: "114",
      name: "Angoliath V",
    },
    {
      id: "swsh3-115",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/115/high.webp",
      localId: "115",
      name: "Angoliath VMAX",
    },
    {
      id: "swsh3-116",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/116/high.webp",
      localId: "116",
      name: "Éthernatos V",
    },
    {
      id: "swsh3-117",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/117/high.webp",
      localId: "117",
      name: "Éthernatos VMAX",
    },
    {
      id: "swsh3-118",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/118/high.webp",
      localId: "118",
      name: "Cizayox V",
    },
    {
      id: "swsh3-119",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/119/high.webp",
      localId: "119",
      name: "Cizayox VMAX",
    },
    {
      id: "swsh3-120",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/120/high.webp",
      localId: "120",
      name: "Airmure",
    },
    {
      id: "swsh3-121",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/121/high.webp",
      localId: "121",
      name: "Galekid",
    },
    {
      id: "swsh3-122",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/122/high.webp",
      localId: "122",
      name: "Galegon",
    },
    {
      id: "swsh3-123",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/123/high.webp",
      localId: "123",
      name: "Galeking",
    },
    {
      id: "swsh3-124",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/124/high.webp",
      localId: "124",
      name: "Lançargot",
    },
    {
      id: "swsh3-125",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/125/high.webp",
      localId: "125",
      name: "Tic",
    },
    {
      id: "swsh3-126",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/126/high.webp",
      localId: "126",
      name: "Clic",
    },
    {
      id: "swsh3-127",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/127/high.webp",
      localId: "127",
      name: "Cliticlic",
    },
    {
      id: "swsh3-128",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/128/high.webp",
      localId: "128",
      name: "Limonde de Galar V",
    },
    {
      id: "swsh3-129",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/129/high.webp",
      localId: "129",
      name: "Meltan",
    },
    {
      id: "swsh3-130",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/130/high.webp",
      localId: "130",
      name: "Melmetal",
    },
    {
      id: "swsh3-131",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/131/high.webp",
      localId: "131",
      name: "Charibari",
    },
    {
      id: "swsh3-132",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/132/high.webp",
      localId: "132",
      name: "Pachyradjah",
    },
    {
      id: "swsh3-133",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/133/high.webp",
      localId: "133",
      name: "Kangourex",
    },
    {
      id: "swsh3-134",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/134/high.webp",
      localId: "134",
      name: "Tauros",
    },
    {
      id: "swsh3-135",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/135/high.webp",
      localId: "135",
      name: "Fouinette",
    },
    {
      id: "swsh3-136",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/136/high.webp",
      localId: "136",
      name: "Fouinar",
    },
    {
      id: "swsh3-137",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/137/high.webp",
      localId: "137",
      name: "Insolourdo",
    },
    {
      id: "swsh3-138",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/138/high.webp",
      localId: "138",
      name: "Teddiursa",
    },
    {
      id: "swsh3-139",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/139/high.webp",
      localId: "139",
      name: "Ursaring",
    },
    {
      id: "swsh3-140",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/140/high.webp",
      localId: "140",
      name: "Lugia",
    },
    {
      id: "swsh3-141",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/141/high.webp",
      localId: "141",
      name: "Skitty",
    },
    {
      id: "swsh3-142",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/142/high.webp",
      localId: "142",
      name: "Delcatty",
    },
    {
      id: "swsh3-143",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/143/high.webp",
      localId: "143",
      name: "Drattak V",
    },
    {
      id: "swsh3-144",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/144/high.webp",
      localId: "144",
      name: "Drattak VMAX",
    },
    {
      id: "swsh3-145",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/145/high.webp",
      localId: "145",
      name: "Étourmi",
    },
    {
      id: "swsh3-146",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/146/high.webp",
      localId: "146",
      name: "Étourvol",
    },
    {
      id: "swsh3-147",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/147/high.webp",
      localId: "147",
      name: "Étouraptor",
    },
    {
      id: "swsh3-148",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/148/high.webp",
      localId: "148",
      name: "Couaneton",
    },
    {
      id: "swsh3-149",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/149/high.webp",
      localId: "149",
      name: "Lakmécygne",
    },
    {
      id: "swsh3-150",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/150/high.webp",
      localId: "150",
      name: "Sapereau",
    },
    {
      id: "swsh3-151",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/151/high.webp",
      localId: "151",
      name: "Passerouge",
    },
    {
      id: "swsh3-152",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/152/high.webp",
      localId: "152",
      name: "Rongourmand",
    },
    {
      id: "swsh3-153",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/153/high.webp",
      localId: "153",
      name: "Rongrigou",
    },
    {
      id: "swsh3-154",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/154/high.webp",
      localId: "154",
      name: "Minisange",
    },
    {
      id: "swsh3-155",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/155/high.webp",
      localId: "155",
      name: "Bleuseille",
    },
    {
      id: "swsh3-156",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/156/high.webp",
      localId: "156",
      name: "Corvaillus",
    },
    {
      id: "swsh3-157",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/157/high.webp",
      localId: "157",
      name: "Ombrelle Géante",
    },
    {
      id: "swsh3-158",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/158/high.webp",
      localId: "158",
      name: "Volutes de Fumée",
    },
    {
      id: "swsh3-159",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/159/high.webp",
      localId: "159",
      name: "Ornithologue",
    },
    {
      id: "swsh3-160",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/160/high.webp",
      localId: "160",
      name: "Cape d'Endurance",
    },
    {
      id: "swsh3-161",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/161/high.webp",
      localId: "161",
      name: "Cloche Familière",
    },
    {
      id: "swsh3-162",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/162/high.webp",
      localId: "162",
      name: "Forêt de Lumirinth",
    },
    {
      id: "swsh3-163",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/163/high.webp",
      localId: "163",
      name: "Kabu",
    },
    {
      id: "swsh3-164",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/164/high.webp",
      localId: "164",
      name: "Vieux PC",
    },
    {
      id: "swsh3-165",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/165/high.webp",
      localId: "165",
      name: "Peterson",
    },
    {
      id: "swsh3-166",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/166/high.webp",
      localId: "166",
      name: "Soins de l'Éleveur de Pokémon",
    },
    {
      id: "swsh3-167",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/167/high.webp",
      localId: "167",
      name: "Fossile Rare",
    },
    {
      id: "swsh3-168",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/168/high.webp",
      localId: "168",
      name: "Shehroz",
    },
    {
      id: "swsh3-169",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/169/high.webp",
      localId: "169",
      name: "Shehroz Tower",
    },
    {
      id: "swsh3-170",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/170/high.webp",
      localId: "170",
      name: "Smashings",
    },
    {
      id: "swsh3-171",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/171/high.webp",
      localId: "171",
      name: "Gants d'Épreuve",
    },
    {
      id: "swsh3-172",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/172/high.webp",
      localId: "172",
      name: "Fortifiant Turbo",
    },
    {
      id: "swsh3-173",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/173/high.webp",
      localId: "173",
      name: "Clairon de la Team Yell",
    },
    {
      id: "swsh3-174",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/174/high.webp",
      localId: "174",
      name: "Énergie Fire Chaleur",
    },
    {
      id: "swsh3-175",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/175/high.webp",
      localId: "175",
      name: "Énergie Darkness Repaire",
    },
    {
      id: "swsh3-176",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/176/high.webp",
      localId: "176",
      name: "Énergie Colorless Puissance",
    },
    {
      id: "swsh3-177",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/177/high.webp",
      localId: "177",
      name: "Papilusion V",
    },
    {
      id: "swsh3-178",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/178/high.webp",
      localId: "178",
      name: "Démolosse V",
    },
    {
      id: "swsh3-179",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/179/high.webp",
      localId: "179",
      name: "Scolocendre V",
    },
    {
      id: "swsh3-180",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/180/high.webp",
      localId: "180",
      name: "Lucanon V",
    },
    {
      id: "swsh3-181",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/181/high.webp",
      localId: "181",
      name: "Rhinastoc V",
    },
    {
      id: "swsh3-182",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/182/high.webp",
      localId: "182",
      name: "Nostenfer V",
    },
    {
      id: "swsh3-183",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/183/high.webp",
      localId: "183",
      name: "Cizayox V",
    },
    {
      id: "swsh3-184",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/184/high.webp",
      localId: "184",
      name: "Limonde de Galar V",
    },
    {
      id: "swsh3-185",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/185/high.webp",
      localId: "185",
      name: "Drattak V",
    },
    {
      id: "swsh3-186",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/186/high.webp",
      localId: "186",
      name: "Kabu",
    },
    {
      id: "swsh3-187",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/187/high.webp",
      localId: "187",
      name: "Peterson",
    },
    {
      id: "swsh3-188",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/188/high.webp",
      localId: "188",
      name: "Soins de l'Éleveur de Pokémon",
    },
    {
      id: "swsh3-189",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/189/high.webp",
      localId: "189",
      name: "Shehroz",
    },
    {
      id: "swsh3-190",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/190/high.webp",
      localId: "190",
      name: "Papilusion VMAX",
    },
    {
      id: "swsh3-191",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/191/high.webp",
      localId: "191",
      name: "Scolocendre VMAX",
    },
    {
      id: "swsh3-192",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/192/high.webp",
      localId: "192",
      name: "Éthernatos VMAX",
    },
    {
      id: "swsh3-193",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/193/high.webp",
      localId: "193",
      name: "Cizayox VMAX",
    },
    {
      id: "swsh3-194",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/194/high.webp",
      localId: "194",
      name: "Drattak VMAX",
    },
    {
      id: "swsh3-195",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/195/high.webp",
      localId: "195",
      name: "Soins de l'Éleveur de Pokémon",
    },
    {
      id: "swsh3-196",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/196/high.webp",
      localId: "196",
      name: "Shehroz",
    },
    {
      id: "swsh3-197",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/197/high.webp",
      localId: "197",
      name: "Gorythmic",
    },
    {
      id: "swsh3-198",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/198/high.webp",
      localId: "198",
      name: "Monthracite",
    },
    {
      id: "swsh3-199",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/199/high.webp",
      localId: "199",
      name: "Ombrelle Géante",
    },
    {
      id: "swsh3-200",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/200/high.webp",
      localId: "200",
      name: "Fortifiant Turbo",
    },
    {
      id: "swsh3-201",
      image: "https://assets.tcgdex.net/fr/swsh/swsh3/201/high.webp",
      localId: "201",
      name: "Énergie Capture",
    },
  ],
};
